# Generated by Django 3.2.9 on 2023-01-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservice',
            options={'verbose_name': 'Категории сервиса', 'verbose_name_plural': 'Категория сервиса'},
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название услуг'),
        ),
    ]
