# Generated by Django 4.1.4 on 2022-12-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$jBZRRVZYo7qzITPUf7kEZg$PtnGDMvQX9XNABIWljzonR+9JFRw6fUz2IX0ICUB9A4=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
