# Generated by Django 4.1.4 on 2022-12-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$TbCHToGG41PF3JjGuF5QjS$5wGOLZ+qDW/3rCF1Mu+rB7ZnMzGsVS21AABuwpWNOfA=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
