# Generated by Django 4.1.4 on 2022-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="snapchat",
        ),
        migrations.RemoveField(
            model_name="user",
            name="wechat",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$EMq7c6UmXNZQmNDKbDfpdL$xSJGJnj63Hae58HbQz2NexiKIO+lM1j9HueKuoG5iWU=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
