# Generated by Django 4.1.4 on 2022-12-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$oP6gpQmyiZF4yk7WOCizQe$qMALe2b6xclsn8x9Mnc0JCsLpSzFppHVbY6xOrx+FB8=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
