# Generated by Django 4.1.4 on 2022-12-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$KL2YhHloEwdTblGCKzWtmC$H5v1fAS6cbddcPlN7+EvJVIcaPsEPNnFOyhrt/pQiuE=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
