# Generated by Django 4.1.4 on 2022-12-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$rRtfNeuw0KHgmWLD1F9Zgq$CUvTASPlRyKzA8YyjpmKBnFVZoFDYHTQzyywu4USm9E=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
