# Generated by Django 4.1.4 on 2022-12-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$WHJd0e43qAqqFoSBKUEgfY$X+1tAbtwV9KCHzDk7lc0aVcb6QGYBo8Lp+nOesXyVWo=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
