# Generated by Django 4.1.4 on 2022-12-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$4lwdydpgbdlYxW8Y6Q0qG7$x4MS6ucyiXOU2L9LHHnvhg+fBf/C99RhJysHfVznUKY=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
