# Generated by Django 4.1.4 on 2022-12-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$SDd4SCAevXFDrJrrCb5OAB$oZgIlwcQYN+14YQPCMRxg7lM03oCWyeiMgtDPL7WcT0=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
