# Generated by Django 4.1.4 on 2022-12-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$fXdMleYfIDgRiXUXxG81ml$xCohd18dWVkgz88YaMSKDRcUxuKNg3aIo7yUaF2BPxI=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
