# Generated by Django 4.1.4 on 2022-12-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$lst1u7lBG69IzPCQMFwSOM$HeFG63pbvkJFZinUR9OnYoh4qpRnbTUHc/bsQ7goQCw=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
