# Generated by Django 4.1.4 on 2023-01-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$kQYtjtGQ4cDzBZyn6NnZAV$B6mqZGfiDU2U/dNDcCl1fNCrKtF0qbXz2k45BQ7B49U=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
