# Generated by Django 4.1.4 on 2023-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$bfIM6Xt9vFXMmhpfib2lxI$Mp2kU3Ie0Dlt3DIbzLCs02MgobxHJbQr8v0stMK2qLE=",
                max_length=128,
                verbose_name="Пароль",
            ),
        ),
    ]
