# Generated by Django 3.2.9 on 2023-01-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$8Kyiij82lfxE0TSZv5BDPA$+aclbt6Py49oAKYqXa/27E7tY4UFiIMAOa3ptCxj3sU=', max_length=128, verbose_name='Пароль'),
        ),
    ]
