# Generated by Django 3.2.9 on 2023-01-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$8lD5c1oC9DroJHFn0ZRtep$YMuRQ8fhYfuNI+V0WXnfXUcMRhtpFXqV6Qlum01lojE=', max_length=128, verbose_name='Пароль'),
        ),
    ]
