# Generated by Django 3.2.9 on 2023-01-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$OMGFKRyE1w4q3FEA19JLfw$KVDCDGunilgqJ7UJY8RvIaxZkwj6qEieKU056/PpFfs=', max_length=128, verbose_name='Пароль'),
        ),
    ]
