# Generated by Django 3.2.9 on 2023-01-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$J0MoRrBC0WfiynD4or35yD$VzIGFyjhQeqULMabo6Uye4OyIySXS/Qz2BIdFI7YSIg=', max_length=128, verbose_name='Пароль'),
        ),
    ]
