# Generated by Django 3.2.9 on 2023-01-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$qBE9KdI5qvtTS7PRlZBfn5$/K7XaceG87/3khV7CkJFJj1nyD/kKIpDzlvJWo3Q18I=', max_length=128, verbose_name='Пароль'),
        ),
    ]
