# Generated by Django 3.2.9 on 2023-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$PjaOSFC2Msvok9EczbLmoO$J2HZYr4ge0iLiqbaKbQBllRhqidf2ZLWc0TxW6HF8Q0=', max_length=128, verbose_name='Пароль'),
        ),
    ]
