# Generated by Django 3.2.9 on 2023-01-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$shnfPPhmdb85OAOVEnsuON$HHZMTEBw3dPXWJ7H+rMgy9yWYeyccnqNt0oDEtTqMiM=', max_length=128, verbose_name='Пароль'),
        ),
    ]
