# Generated by Django 3.2.9 on 2023-01-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$dGzzFblEXUVlhHVooqcLRn$2foqOG+4TlIDbNGms1ohCwvfufuwYxQE0H7c+5b40yQ=', max_length=128, verbose_name='Пароль'),
        ),
    ]
