# Generated by Django 4.1.4 on 2023-01-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категория",
                "db_table": "category_home",
            },
        ),
        migrations.AddField(
            model_name="realestate",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="address",
            field=models.CharField(max_length=32, verbose_name="Адрес"),
        ),
        migrations.CreateModel(
            name="ImageHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/car", verbose_name="Фотография"
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.realestate",
                        verbose_name="Недвижимость",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото",
                "verbose_name_plural": "фотографии",
                "db_table": "home_image",
            },
        ),
        migrations.AddField(
            model_name="realestate",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.categoryhome",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
