# Generated by Django 3.2.9 on 2023-01-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categoryhome_realestate_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryhome',
            options={'verbose_name': 'Категория недвижимость', 'verbose_name_plural': 'Категория недвижимости'},
        ),
    ]
