# Generated by Django 3.2.9 on 2023-01-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_categoryhome_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='seller_type',
            field=models.CharField(blank=True, choices=[['Собственник', 'Собственник'], ['Агенство', 'Агенство']], default=None, max_length=100, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Заголовок объявления'),
        ),
    ]
