# Generated by Django 3.2.9 on 2023-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230126_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='balcony',
            field=models.CharField(blank=True, choices=[['Нет балкона', 'Нет балкона'], ['Балкон', 'Балкон'], ['Лоджия', 'Лоджия']], default=None, max_length=32, null=True, verbose_name='Выберите тип балкона'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='bathroom',
            field=models.CharField(blank=True, choices=[['Совмещённый', 'Совмещённый'], ['Раздельный', 'Раздельный']], default=None, max_length=100, null=True, verbose_name='Выберите тип санузла'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='floor_home',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажей в доме'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='living_space',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='material',
            field=models.CharField(blank=True, choices=[['Кирпич', 'Кирпич'], ['Монолит', 'Монолит'], ['Кирпич-монолит', 'Кирпич-монолит'], ['Панель', 'Панель'], ['Блок', 'Блок']], default=None, max_length=100, null=True, verbose_name='Выберите материал'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='parking',
            field=models.CharField(blank=True, choices=[['Нет', 'Нет'], ['Подземная', 'Подземная'], ['Охраняемая', 'Охраняемая'], ['Отдельная', 'Отдельная'], ['Рядом', 'Рядом']], default=None, max_length=32, null=True, verbose_name='Выберите тип парковки'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='repair',
            field=models.CharField(blank=True, choices=[['Обычный', 'Обычный'], ['Косметический', 'Косметический'], ['Евро', 'Евро'], ['Дизайнерский', 'Дизайнерский'], ['Требуется ремонт', 'Требуется ремонт']], default=None, max_length=32, null=True, verbose_name='Выберите тип ремонта'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='total_area',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Общая площадь'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='years',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='seller_type',
            field=models.CharField(blank=True, choices=[['Собственник', 'Собственник'], ['Агенство', 'Агенство']], default=None, max_length=100, null=True, verbose_name='Тип продавца'),
        ),
    ]
