# Generated by Django 3.2.9 on 2023-01-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230127_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='conditioning',
            field=models.BooleanField(default=False, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='consumer_electronics',
            field=models.BooleanField(default=False, verbose_name='Бытовая электроника'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='Лифт'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='furniture',
            field=models.BooleanField(default=False, verbose_name='Мебель'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='garbage_chute',
            field=models.BooleanField(default=False, verbose_name='Мусоропровод'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='internet',
            field=models.BooleanField(default=False, verbose_name='Интернет'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='negotiable',
            field=models.BooleanField(default=False, verbose_name='Договорная'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='refrigerator',
            field=models.BooleanField(default=False, verbose_name='Холодильник'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='security',
            field=models.BooleanField(default=False, verbose_name='Охрана'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Как можно подробнее опишите Ваш объект недвижимости'),
        ),
    ]
