# Generated by Django 3.2.9 on 2023-01-30 12:05

import apps.home.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230128_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryhome',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=apps.home.services.get_upload_path, validators=[apps.home.services.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='categoryhome',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.home.services.get_upload_path),
        ),
        migrations.AddField(
            model_name='categoryhome',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryhome',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='home.categoryhome'),
        ),
        migrations.AlterField(
            model_name='categoryhome',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
    ]
