# Generated by Django 4.1.4 on 2022-12-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_category_logo_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(upload_to="images/bannre", verbose_name=""),
                ),
                ("url", models.URLField(verbose_name="Укажите url ссылку")),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
                "db_table": "banner",
            },
        ),
    ]
