# Generated by Django 4.1.4 on 2022-12-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_bannerone_bannerthree_bannertwo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bannerfour",
            options={"verbose_name": "Баннер", "verbose_name_plural": "Баннеры_4"},
        ),
        migrations.AlterModelOptions(
            name="bannerone",
            options={"verbose_name": "Баннер", "verbose_name_plural": "Баннеры_1"},
        ),
        migrations.AlterModelOptions(
            name="bannerthree",
            options={"verbose_name": "Баннер", "verbose_name_plural": "Баннеры_3"},
        ),
        migrations.AlterModelOptions(
            name="bannertwo",
            options={"verbose_name": "Баннер", "verbose_name_plural": "Баннеры_2"},
        ),
        migrations.AddField(
            model_name="product",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[["Б/у", "Б/у"], ["Новое", "Новое"]],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Состояние автомобиля",
            ),
        ),
    ]
