# Generated by Django 4.1.4 on 2022-12-28 08:31

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_alter_bannerfour_options_alter_bannerone_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Размер"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[["Б/у", "Б/у"], ["Новое", "Новое"]],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Состояние",
            ),
        ),
        migrations.CreateModel(
            name="ImageProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        upload_to="images/prod", verbose_name="Фотография"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото продукта",
                "verbose_name_plural": "Фотографии продукта",
                "db_table": "prod_image",
            },
        ),
    ]
