# Generated by Django 4.1.4 on 2023-01-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_product_color_product_description_product_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerfour",
            name="images",
            field=models.ImageField(
                upload_to="images/bannre",
                verbose_name="Фотография: *pекомендация(1440x530)",
            ),
        ),
        migrations.AlterField(
            model_name="bannerone",
            name="images",
            field=models.ImageField(
                upload_to="images/bannre",
                verbose_name="Фотография: *pекомендация(1440x530)",
            ),
        ),
        migrations.AlterField(
            model_name="bannerthree",
            name="images",
            field=models.ImageField(
                upload_to="images/bannre",
                verbose_name="Фотография: *pекомендация(1440x530)",
            ),
        ),
        migrations.AlterField(
            model_name="bannertwo",
            name="images",
            field=models.ImageField(
                upload_to="images/bannre",
                verbose_name="Фотография: *pекомендация(1440x530)",
            ),
        ),
    ]
