# Generated by Django 4.1.4 on 2022-12-24 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Категория работ"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/logo/job",
                        verbose_name="Фотография",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория работ",
                "verbose_name_plural": "Категории работ",
                "db_table": "categoryjob",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название работ"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/job",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "release_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата публикации"),
                ),
                (
                    "price",
                    models.CharField(
                        default="Договорная", max_length=100, verbose_name="Цена"
                    ),
                ),
                (
                    "category_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.categoryjob",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
                "db_table": "job",
            },
        ),
    ]
