# Generated by Django 4.1.4 on 2022-12-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="body_car",
            field=models.CharField(
                blank=True,
                choices=[
                    ["Седан", "Седан"],
                    ["Универсал", "Универсал"],
                    ["Хэтчбек", "Хэтчбек"],
                    ["Лифтбек", "Лифтбек"],
                    ["Лимузин", "Лимузин"],
                    ["Внедорожник", "Внедорожник"],
                    ["Кроссовер", "Кроссовер"],
                    ["Стретч", "Стретч"],
                    ["Купе", "Купе"],
                    ["Кабриолет", "Кабриолет"],
                    ["Родстер", "Родстер"],
                    ["Тарга", "Тарга"],
                    ["Пикап", "Пикап"],
                    ["Фургон", "Фургон"],
                    ["Минивэн", "Минивэн"],
                ],
                default="Седан",
                max_length=100,
                null=True,
                verbose_name="Тип кузова",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.CharField(
                blank=True,
                choices=[
                    ["Бензиновый", "Бензиновый"],
                    ["Дизельный", "Дизельный"],
                    ["Гибридный", "Гибридный"],
                    ["Газ", "Газ"],
                    ["Электрический", "Электрический"],
                ],
                default="Бензиновый",
                max_length=100,
                null=True,
                verbose_name="Тип двигателя",
            ),
        ),
    ]
