# Generated by Django 4.1.4 on 2022-12-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_alter_car_body_car_alter_car_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="name",
            field=models.CharField(
                default=1, max_length=200, verbose_name="Название автомобиля"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ["Отличное", "Отличное"],
                    ["Среднее", "Среднее"],
                    ["Плохое", "Плохое"],
                ],
                default="Отличное",
                max_length=100,
                null=True,
                verbose_name="Состояние автомобиля",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[
                    ["Механическая", "Механическая"],
                    ["Автоматическая", "Автоматическая"],
                    ["Роботизированная", "Роботизированная"],
                    ["Вариативная (бесступенчатая)", "Вариативная (бесступенчатая)"],
                ],
                default="Механическая",
                max_length=100,
                null=True,
                verbose_name="Коробка передач",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="category_car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="car.categorycar",
                verbose_name="Марка автомобиля",
            ),
        ),
    ]
