# Generated by Django 4.1.4 on 2022-12-18 16:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0003_car_name_car_state_car_transmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="drive_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ["Передний привод", "Передний привод"],
                    ["Задний привод", "Задний привод"],
                    ["Полный привод", "Полный привод"],
                    [
                        "Гибридный синергетический привод",
                        "Гибридный синергетический привод",
                    ],
                ],
                default="Передний привод",
                max_length=100,
                null=True,
                verbose_name="Привод",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="steering_wheel",
            field=models.CharField(
                blank=True,
                choices=[["Правый", "Правый"], ["Левый", "Левый"]],
                default="Правый",
                max_length=100,
                null=True,
                verbose_name="Руль",
            ),
        ),
    ]
