# Generated by Django 4.1.4 on 2022-12-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0004_car_color_car_drive_unit_car_steering_wheel"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.TextField(default=1, verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.BigIntegerField(default=1, verbose_name="Цена"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.BigIntegerField(default=1, verbose_name="Год выпуска"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="drive_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ["Передний привод", "Передний привод"],
                    ["Задний привод", "Задний привод"],
                    ["Полный привод", "Полный привод"],
                    ["Гибридный привод", "Гибридный привод"],
                ],
                default="Передний привод",
                max_length=100,
                null=True,
                verbose_name="Привод",
            ),
        ),
        migrations.AlterField(
            model_name="categorycar",
            name="logo",
            field=models.ImageField(upload_to="imageslogo", verbose_name="Фотография"),
        ),
        migrations.CreateModel(
            name="ImageCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_one",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/car",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "image_two",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/car",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "image_three",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/car",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "image_four",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/car",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "image_five",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/car",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "image_six",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/car",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "image_seven",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/car",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "image_eight",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/car",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car.car",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото машин",
                "verbose_name_plural": "фотографии машин",
                "db_table": "car_image",
            },
        ),
    ]
