# Generated by Django 4.1.4 on 2022-12-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0007_car_mileage_car_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorycar",
            name="logo",
            field=models.ImageField(upload_to="images/logo", verbose_name="Фотография"),
        ),
    ]
