# Generated by Django 4.1.4 on 2022-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0008_alter_categorycar_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorycar",
            options={
                "verbose_name": "Категория машин",
                "verbose_name_plural": "Категории машин",
            },
        ),
        migrations.AlterField(
            model_name="categorycar",
            name="logo",
            field=models.ImageField(
                upload_to="images/logo/car", verbose_name="Фотография"
            ),
        ),
    ]
