# Generated by Django 4.1.4 on 2022-12-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0010_rename_image_one_imagecar_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="imagecar",
            name="image",
            field=models.ImageField(
                default=1, upload_to="images/car", verbose_name="Фотография"
            ),
            preserve_default=False,
        ),
    ]
