# Generated by Django 3.2.9 on 2023-01-23 09:36

import apps.car.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_car_price_alter_imagecar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.car.services.get_upload_path)),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps.car.services.get_upload_path, validators=[apps.car.services.validate_file_extension])),
                ('is_main', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='car.category')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='category_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.category', verbose_name='Марка автомобиля'),
        ),
        migrations.DeleteModel(
            name='CategoryCar',
        ),
    ]
