# Generated by Django 3.2.9 on 2023-01-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_auto_20230123_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_ar',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
    ]
