# Generated by Django 3.2.9 on 2023-01-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_auto_20230124_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория машин', 'verbose_name_plural': 'Категории машин'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categorycar',
        ),
    ]
