# Generated by Django 3.2.9 on 2023-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_auto_20230124_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_power',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='address',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Адрес стоянки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Объем двигателя'),
        ),
    ]
